# Generated by Django 3.1.1 on 2021-06-26 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='empname',
        ),
    ]
