# Generated by Django 3.1.1 on 2021-06-26 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_auto_20210626_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='dept_name',
            new_name='deptname',
        ),
    ]
